app:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/sanrenxing
    username: postgres
    password: password
    pool-size: 30
  sql:
    init:
      mode: always
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    root: INFO
    com.sanrenxing.service: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

