app:
  datasource:
    jdbcUrl: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool-size: 30
  sql:
    init:
      mode: always
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
