app:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/sanrenxing
    username: postgres
    password: sanrenxing
    pool-size: 30
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG