server:
  error:
    include-message: always
    include-binding-errors: always
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/sanrenxing
    username: postgres
    password: password
    pool-size: 30
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG